library(tidyverse)

cat("\n╔════════════════════════════════════════════════════════════════╗\n")
cat("║  ORDINAL AWARENESS SCALE: FINAL ANALYSIS & RECOMMENDATION     ║\n")
cat("╚════════════════════════════════════════════════════════════════╝\n\n")

# Load results
ordinal_summary <- read_csv("v2_pipeline/C_STRUCTURAL_MODELS/outputs/03_ordinal_combined_summary.csv")
old_comparison <- read_csv("ordinal_vs_binary_fit_comparison.csv")

cat("RESEARCH QUESTION:\n")
cat("─────────────────────────────────────────────────────────────────\n")
cat("Would collapsing TOM/SAW (binary) into an ordinal 3-level scale\n")
cat("improve model fit for Faircloth and Boenigk brand equity models?\n\n")

cat("FINDINGS:\n")
cat("═════════════════════════════════════════════════════════════════\n\n")

cat("1. FAIRCLOTH: ORDINAL AWARENESS IMPROVES FIT ✓\n\n")
cat("   Comparison (single outcome: OF02_01_num):\n")
print(old_comparison %>% filter(Architecture == "Faircloth"))
cat("\n   Detailed Results (All Outcomes):\n")
print(ordinal_summary %>% filter(Model == "FC-Ordinal-Separate"))
cat("\n   Interpretation:\n")
cat("   ✓ Ordinal awareness consistently outperforms binary TOM/SAW\n")
cat("   ✓ CFI improvement: 0.9488 → 0.9813 for main outcome (+3.25pp)\n")
cat("   ✓ RMSEA improvement: 0.0715 → 0.0509 (smaller is better)\n")
cat("   ✓ Faircloth models with OF02_01, OF02_02, OF02_03 all converge\n")
cat("   ⚠ Mixed estimators (WLSMV with continuous outcomes) cause\n")
cat("     identification issues for OF01/OF_Spender/Combined models\n\n")

cat("2. BOENIGK: ORDINAL AWARENESS SLIGHTLY WORSE\n\n")
cat("   Comparison (single outcome: OF02_01_num):\n")
print(old_comparison %>% filter(Architecture == "Boenigk"))
cat("\n   Interpretation:\n")
cat("   ⚠ Ordinal awareness slightly reduces CFI: 0.9941 → 0.9900 (-0.4pp)\n")
cat("   • Both are excellent (CFI > 0.99)\n")
cat("   • Boenigk already optimal with binary TOM/SAW approach\n")
cat("   • MLR already handles the awareness items well\n\n")

cat("═════════════════════════════════════════════════════════════════\n")
cat("THEORETICAL JUSTIFICATION:\n")
cat("═════════════════════════════════════════════════════════════════\n\n")

cat("WHY ORDINAL AWARENESS WORKS:\n\n")
cat("1. Theory: Awareness is inherently ordinal\n")
cat("   - Level 1: No spontaneous awareness (baseline)\n")
cat("   - Level 2: Spontaneous awareness (SAW, unaided recall)\n")
cat("   - Level 3: Top-of-mind (TOM, highest awareness)\n")
cat("   - This is a CONTINUUM, not two discrete binary traits\n\n")

cat("2. Measurement: Ordinal items need ordinal estimator\n")
cat("   - WLSMV (Weighted Least Squares Mean/Variance)\n")
cat("   - Proper handling of categorical/ordinal structure\n")
cat("   - Reduces measurement error from treating ordinal as continuous\n\n")

cat("3. Empirical: Faircloth fit improves significantly\n")
cat("   - Δ CFI = +0.0325 is meaningful (> typical 0.01 threshold)\n")
cat("   - Lower RMSEA indicates better fit\n")
cat("   - Suggests ordinal structure captures awareness better\n\n")

cat("═════════════════════════════════════════════════════════════════\n")
cat("WHY BOENIGK DOESN'T IMPROVE:\n")
cat("═════════════════════════════════════════════════════════════════\n\n")

cat("1. Ceiling effect: Boenigk already excellent\n")
cat("   - CFI = 0.9941 is near-maximum fit\n")
cat("   - Little room for improvement\n\n")

cat("2. Robust estimation: MLR with FIML is strong\n")
cat("   - Handles missing data well\n")
cat("   - Binary formulation works despite ordinality\n\n")

cat("3. Factor structure: Boenigk items may have different properties\n")
cat("   - Different correlation patterns vs. Faircloth\n")
cat("   - Binary treatment may actually fit better\n\n")

cat("═════════════════════════════════════════════════════════════════\n")
cat("RECOMMENDATION:\n")
cat("═════════════════════════════════════════════════════════════════\n\n")

cat("ADOPT HYBRID STRATEGY:\n\n")

cat("✓ USE ORDINAL RC_AWARENESS FOR FAIRCLOTH:\n")
cat("  - Model specification:\n")
cat("    FC_RC =~ RC_Awareness  (instead of TOM + SAW)\n")
cat("  - Estimator: WLSMV (for ordinal/categorical variables)\n")
cat("  - Outcomes: OF02_01_num, OF02_02_num, OF02_03_num (✓ working)\n")
cat("  - Benefits:\n")
cat("    • Better fit (CFI +3.25pp)\n")
cat("    • Theoretically aligned with awareness hierarchy\n")
cat("    • WLSMV appropriately handles ordinality\n\n")

cat("  ⚠ Known limitation:\n")
cat("    • Mixed estimators (WLSMV + continuous outcomes) cause\n")
cat("      identification issues\n")
cat("    • Can estimate separately (not as combined multivariate)\n")
cat("    • Cannot use with OF01 or OF_Spender in same model\n\n")

cat("✓ KEEP BINARY TOM/SAW FOR BOENIGK:\n")
cat("  - Model specification:\n")
cat("    BO_RC =~ TOM + SAW  (unchanged)\n")
cat("  - Estimator: MLR (continuous)\n")
cat("  - Outcomes: All (OF02_01/02/03, OF01, OF_Spender)\n")
cat("  - Rationale:\n")
cat("    • Already optimal (CFI = 0.9941)\n")
cat("    • Ordinal switch provides no improvement\n")
cat("    • Avoids identification issues\n\n")

cat("═════════════════════════════════════════════════════════════════\n")
cat("NEXT STEPS FOR PRODUCTION:\n")
cat("═════════════════════════════════════════════════════════════════\n\n")

cat("1. Update Faircloth model formulas in Phase C to use RC_Awareness\n")
cat("2. Keep Boenigk on binary TOM/SAW approach\n")
cat("3. Document this architectural choice in README\n")
cat("4. Re-estimate all Faircloth models (currently estimated)\n")
cat("5. Proceed with Phase D (Multi-Group SEM) using hybrid models\n")
cat("6. Include sensitivity analysis comparing both approaches\n\n")

cat("FILES TO KEEP:\n")
cat("───────────────────────────────────────────────────────────────\n")
cat("✓ pipeline_data_fc_bo_with_ordinal_awareness.rds\n")
cat("  (Data with RC_Awareness ordinal variable)\n")
cat("✓ ordinal_vs_binary_fit_comparison.csv\n")
cat("  (Initial comparison test results)\n")
cat("✓ 03_ordinal_combined_summary.csv\n")
cat("  (Faircloth ordinal models results)\n")
cat("✓ sem_fc_ordinal_sep_*.rds\n")
cat("  (Faircloth ordinal models fitted objects)\n\n")

