#!/usr/bin/env python3
"""
Queue Analyzer: Automatically generates new analysis jobs based on results.
- Reads completed analysis outputs
- Decides which follow-up analyses to run
- Pushes new .R scripts to queue/pending/
"""

import json
import re
from pathlib import Path
import logging

PIPELINE_ROOT = "/home/gerald/R-pipeline"
QUEUE_DIR = Path(PIPELINE_ROOT) / "queue"
PENDING_DIR = QUEUE_DIR / "pending"
META_DIR = QUEUE_DIR / "meta"
LOG_DIR = Path(PIPELINE_ROOT) / "logs"

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] %(levelname)s: %(message)s",
    handlers=[
        logging.FileHandler(LOG_DIR / "queue_analyzer.log"),
    ]
)
logger = logging.getLogger(__name__)


def add_to_queue(script_name, script_content):
    """Add a new .R script to queue/pending/."""
    script_path = PENDING_DIR / script_name
    if script_path.exists():
        logger.warning(f"Script already exists, skipping: {script_name}")
        return False

    try:
        with open(script_path, "w") as f:
            f.write(script_content)
        logger.info(f"✅ Added to queue: {script_name}")
        return True
    except Exception as e:
        logger.error(f"Error adding to queue: {e}")
        return False


def parse_log_file(log_path):
    """Parse output log file and extract key metrics."""
    try:
        with open(log_path, "r") as f:
            content = f.read()
        return content
    except Exception as e:
        logger.error(f"Error reading log: {e}")
        return None


# ============================================================================
# Analysis-specific logic
# ============================================================================

def analyze_bsem_results(script_name, stdout, stderr):
    """
    Analyze BSEM (Bayesian SEM) results and suggest follow-ups.
    """
    # Look for interesting patterns
    if "Rhat" in stdout and "converged" in stdout.lower():
        logger.info(f"BSEM {script_name}: Models converged, checking for subgroups...")

        # Check if we should add subgroup analyses
        if "gender" in stdout.lower() or "gender" in stderr.lower():
            # Add gender subgroup analysis
            add_subgroup_analysis(script_name, "gender")

        if "organization_type" in stdout.lower():
            add_subgroup_analysis(script_name, "organization_type")


def analyze_robma_results(script_name, stdout, stderr):
    """
    Analyze RoBMA (Bayesian Meta-Analysis) results.
    """
    if "publication_bias" in stdout.lower():
        logger.info(f"RoBMA {script_name}: Detected publication bias signal")
        # Add sensitivity analysis
        add_trim_and_fill(script_name)


def analyze_elasticnet_results(script_name, stdout, stderr):
    """
    Analyze ElasticNet results and suggest feature validation.
    """
    # Extract top features
    logger.info(f"ElasticNet {script_name}: Checking feature importance...")

    # Look for important features in output
    # Could parse coefficients and suggest feature-interaction analyses


def analyze_dominance_results(script_name, stdout, stderr):
    """
    Analyze dominance analysis results.
    """
    logger.info(f"Dominance {script_name}: Complete")
    # Could check if any variables have high dominance and suggest deeper analysis


# ============================================================================
# Helper functions to generate new analyses
# ============================================================================

def add_subgroup_analysis(base_script, subgroup_var):
    """Generate a subgroup analysis script."""
    # Example: if base_script is "003_bsem_faircloth.R" and subgroup_var is "gender"
    # Create "003b_bsem_faircloth_subgroup_gender.R"

    if subgroup_var not in ["gender", "organization_type"]:
        return

    base_name = Path(base_script).stem
    new_name = f"{base_name}_subgroup_{subgroup_var}.R"

    script_content = f"""#!/usr/bin/env Rscript
# Auto-generated subgroup analysis for {subgroup_var}
# Base: {base_script}
# Generated by queue_analyzer

library(tidyverse)
library(blavaan)

message("[", Sys.time(), "] Starting subgroup analysis: {subgroup_var}")

# Load base data and model results
# (assumes base analysis already completed and saved)

# TODO: Load results from queue/done/{base_script}.log
# TODO: Extract subgroup-specific data
# TODO: Re-fit model stratified by {subgroup_var}
# TODO: Compare results

message("[", Sys.time(), "] Completed subgroup analysis: {subgroup_var}")
"""

    add_to_queue(new_name, script_content)


def add_trim_and_fill(base_script):
    """Generate a trim-and-fill sensitivity analysis."""
    base_name = Path(base_script).stem
    new_name = f"{base_name}_trim_fill.R"

    script_content = f"""#!/usr/bin/env Rscript
# Auto-generated trim-and-fill analysis
# Base: {base_script}
# Generated by queue_analyzer

library(tidyverse)
library(RoBMA)

message("[", Sys.time(), "] Starting trim-and-fill analysis")

# Load RoBMA results from {base_script}
# Run trim-and-fill procedure
# Save sensitivity results

message("[", Sys.time(), "] Completed trim-and-fill analysis")
"""

    add_to_queue(new_name, script_content)


def add_sensitivity_analysis(base_script):
    """Generate a prior sensitivity analysis."""
    base_name = Path(base_script).stem
    new_name = f"{base_name}_sensitivity.R"

    script_content = f"""#!/usr/bin/env Rscript
# Auto-generated sensitivity analysis (priors)
# Base: {base_script}
# Generated by queue_analyzer

message("[", Sys.time(), "] Starting prior sensitivity analysis")

# Re-fit with alternative priors
# Compare to base results
# Document robustness

message("[", Sys.time(), "] Completed sensitivity analysis")
"""

    add_to_queue(new_name, script_content)


# ============================================================================
# Main analyzer entry point
# ============================================================================

def analyze_results(script_name, stdout, stderr):
    """
    Main analyzer function called after each successful job.
    Decides what follow-up analyses to add.
    """
    logger.info(f"Analyzing results from: {script_name}")

    # Route to appropriate analyzer
    if "bsem" in script_name.lower():
        analyze_bsem_results(script_name, stdout, stderr)
    elif "robma" in script_name.lower():
        analyze_robma_results(script_name, stdout, stderr)
    elif "elasticnet" in script_name.lower():
        analyze_elasticnet_results(script_name, stdout, stderr)
    elif "dominance" in script_name.lower():
        analyze_dominance_results(script_name, stdout, stderr)

    logger.info(f"Analysis complete for: {script_name}")


if __name__ == "__main__":
    # For testing
    logger.info("Queue Analyzer module loaded")
